notifications:
  email: false

language: node_js

node_js:
  - "node"

script:
  - npm run build

before_deploy:
  - export JS_PKG_FILE=$(ls dist/*.js)
deploy:
  provider: script
  script: scripts/deploy.sh
  file_glob: true
  on:
    branch: js/refactor

